### ISSUE TITLE
gorse-in-one又遇到一个pannic

### ISSUE THREAD

**Issue by ppyupp** [gorse-io/gorse#487]
version:
clone当前源代码, 自行编译

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x15a79de]

goroutine 74 [running]:
github.com/zhenghaoz/gorse/model/click.(*FM).Predict(0xc000882510, {0x3642de8?, 0x0?}, {0x3642e00, 0x1}, {0xc000887ac0, 0x1, 0xc00012e000?}, {0xc0006b2240, 0x3, ...})
	Users/ak47/dec/gorse-master/model/click/model.go:201 +0x5e
github.com/zhenghaoz/gorse/worker.(*Worker).rankByClickTroughRate(0xc0003bc000, 0xc0006fe998, {0xc00039f9b0, 0x2, 0x0?}, 0xc000a90030)
	Users/ak47/dec/gorse-master/worker/worker.go:842 +0x23c
github.com/zhenghaoz/gorse/worker.(*Worker).Recommend.func2(0xc000756000?, 0x0)
	Users/ak47/dec/gorse-master/worker/worker.go:653 +0x33b3
github.com/zhenghaoz/gorse/base/parallel.Parallel(0x2, 0xc000a90260?, 0xc00060e5a0)
	Users/ak47/dec/gorse-master/base/parallel/parallel.go:31 +0xff
github.com/zhenghaoz/gorse/worker.(*Worker).Recommend(0xc0003bc000, {0xc000561c20, 0x2, 0x2})
	Users/ak47/dec/gorse-master/worker/worker.go:441 +0xf2a
github.com/zhenghaoz/gorse/worker.(*Worker).Serve.func1()
	Users/ak47/dec/gorse-master/worker/worker.go:319 +0x37c
github.com/zhenghaoz/gorse/worker.(*Worker).Serve(0xc0003bc000)
	Users/ak47/dec/gorse-master/worker/worker.go:325 +0xced
main.glob..func1.1()
	Users/ak47/dec/gorse-master/cmd/gorse-in-one/main.go:115 +0xc5
created by main.glob..func1
	Users/ak47/dec/gorse-master/cmd/gorse-in-one/main.go:109 +0xa9d

**Comment by zhenghaoz** [comment]
单节点版本绕过了原先同步模型的流程，出现了很多BUG:cry:

**Comment by ppyupp** [comment]
慢慢打磨 我先试试多节点
