### ISSUE TITLE
gorse-in-one在Windows启动时报错

### ISSUE THREAD

**Issue by wofbi** [gorse-io/gorse#491]
**Gorse version**

Gorse v0.4.4  Windows  gorse-in-one

**Describe the bug**
开发环境在windows11上写了个脚本开机自启gorse,然后刚刚启动的时候看起来没问题,过两分钟就报错退出了

脚本完整内容,timeout 可以忽略:
```
@echo off
start cmd /k "timeout /nobreak /t 10 && cd /d "C:\Program Files\Gorse" && gorse -c  config.toml"
```
似乎是worker在**start building ranking index**的时候报错的?
报错内容如下:
```
{"level":"info","ts":1657160152.242448,"caller":"gorse-in-one/main.go:54","msg":"load config","config":"config.toml"}
{"level":"info","ts":1657160152.2440443,"caller":"master/local_cache.go:46","msg":"load cache","path":"master_cache.data"}
{"level":"info","ts":1657160152.2440443,"caller":"master/master.go:141","msg":"no local cache found, create a new one","path":"master_cache.data"}
{"level":"info","ts":1657160152.244563,"caller":"worker/worker.go:287","msg":"start worker","n_jobs":1,"worker_name":"zealous_poincare"}
{"level":"info","ts":1657160152.244563,"caller":"server/server.go:98","msg":"start server","server_name":"funny_buck","server_host":"0.0.0.0","server_port":8087,"master_host":"0.0.0.0","master_port":8086}
{"level":"info","ts":1657160152.2454643,"caller":"server/rest.go:76","msg":"start http server","url":"http://0.0.0.0:8087"}
{"level":"info","ts":1657160152.44842,"caller":"master/master.go:213","msg":"start model fit","period":3600}
{"level":"info","ts":1657160152.44842,"caller":"master/master.go:215","msg":"start model searcher","period":21600}
{"level":"info","ts":1657160152.44842,"caller":"master/tasks.go:62","msg":"load dataset","positive_feedback_types":["upvote","coin"],"read_feedback_types":["read"],"item_ttl":0,"feedback_ttl":0}
{"level":"info","ts":1657160152.44842,"caller":"master/master.go:219","msg":"start rpc server","host":"0.0.0.0","port":8086}
{"level":"info","ts":1657160152.449439,"caller":"server/rest.go:76","msg":"start http server","url":"http://0.0.0.0:8088"}
{"level":"info","ts":1657160152.4569557,"caller":"master/tasks.go:816","msg":"start fitting ranking model","n_jobs":1}
{"level":"info","ts":1657160152.4569557,"caller":"master/tasks.go:196","msg":"start searching neighbors of items","n_cache":100}
{"level":"info","ts":1657160152.4574604,"caller":"search/ivf.go:279","msg":"try to build vector index","index_type":"IVF","num_probe":17,"recall":0,"build_time":"0s"}
{"level":"info","ts":1657160152.4580307,"caller":"search/ivf.go:279","msg":"try to build vector index","index_type":"IVF","num_probe":34,"recall":0,"build_time":"0s"}
{"level":"info","ts":1657160152.4580307,"caller":"search/ivf.go:279","msg":"try to build vector index","index_type":"IVF","num_probe":68,"recall":0,"build_time":"0s"}
{"level":"info","ts":1657160152.485413,"caller":"master/tasks.go:269","msg":"complete searching neighbors of items","search_time":"27.9076ms"}
{"level":"info","ts":1657160152.485488,"caller":"master/tasks.go:449","msg":"start searching neighbors of users","n_cache":100}
{"level":"info","ts":1657160152.485488,"caller":"search/ivf.go:279","msg":"try to build vector index","index_type":"IVF","num_probe":100,"recall":0,"build_time":"0s"}
{"level":"info","ts":1657160152.485488,"caller":"search/ivf.go:279","msg":"try to build vector index","index_type":"IVF","num_probe":200,"recall":0,"build_time":"0s"}
{"level":"info","ts":1657160152.485488,"caller":"search/ivf.go:279","msg":"try to build vector index","index_type":"IVF","num_probe":400,"recall":0,"build_time":"0s"}
arch_time":"1.2799ms"}
{"level":"info","ts":1657160152.4874604,"caller":"master/tasks.go:928","msg":"prepare to fit click model","n_jobs":1}
{"level":"warn","ts":1657160152.4874604,"caller":"master/tasks.go:937","msg":"empty ranking dataset","positive_feedback_type":["upvote","coin"]}
{"level":"info","ts":1657160152.4874604,"caller":"master/tasks.go:1090","msg":"start cache garbage collection"}
{"level":"info","ts":1657160152.4930878,"caller":"master/tasks.go:1017","msg":"start searching ranking model"}
{"level":"warn","ts":1657160152.4930878,"caller":"master/tasks.go:1025","msg":"empty ranking dataset","positive_feedback_type":["upvote","coin"]}
{"level":"info","ts":1657160152.4935918,"caller":"master/tasks.go:1054","msg":"start searching click model"}
{"level":"warn","ts":1657160152.4935918,"caller":"master/tasks.go:1062","msg":"empty click dataset","positive_feedback_type":["upvote","coin"]}
{"level":"info","ts":1657160212.2528598,"caller":"worker/worker.go:342","msg":"ranking recommendation","n_working_users":1,"n_jobs":1,"cache_size":100}
{"level":"info","ts":1657160212.254026,"caller":"worker/worker.go:369","msg":"start building ranking index"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x12becac]

goroutine 27 [running]:
github.com/zhenghaoz/gorse/worker.(*Worker).Recommend(0xc0003ce000, {0xc000181e00, 0x1, 0x1})
        /home/runner/work/gorse/gorse/worker/worker.go:371 +0x76c
github.com/zhenghaoz/gorse/worker.(*Worker).Serve.func1()
        /home/runner/work/gorse/gorse/worker/worker.go:318 +0x37c
github.com/zhenghaoz/gorse/worker.(*Worker).Serve(0xc0003ce000)
        /home/runner/work/gorse/gorse/worker/worker.go:324 +0xced
main.glob..func1.1()
        /home/runner/work/gorse/gorse/cmd/gorse-in-one/main.go:70 +0xc5
created by main.glob..func1
        /home/runner/work/gorse/gorse/cmd/gorse-in-one/main.go:64 +0x47d
```

**Comment by wofbi** [comment]
刚刚试了一下,似乎与是否是开机自启无关,手动启动也有这个问题
