### ISSUE TITLE
panic: runtime error: index out of range [207] with length 206

### ISSUE THREAD

**Issue by andresribeiro** [gorse-io/gorse#692]
```shell
{"level":"info","ts":1685395677.9141247,"msg":"start searching neighbors of items","n_cache":200}
panic: runtime error: index out of range [-1]

goroutine 88 [running]:
github.com/zhenghaoz/gorse/base/search.(*IVF).Build.func1(0x50?, 0x5)
	/go/gorse/base/search/ivf.go:222 +0x385
github.com/zhenghaoz/gorse/base/parallel.Parallel(0x95, 0xc000b98a80?, 0xc000e1e1e0)
	/go/gorse/base/parallel/parallel.go:39 +0xf7
github.com/zhenghaoz/gorse/base/search.(*IVF).Build(0xc0009352c0)
	/go/gorse/base/search/ivf.go:209 +0x525
github.com/zhenghaoz/gorse/base/search.(*IVFBuilder).Build(0xc000e1e190, 0x3f4ccccd, 0x3, 0xc8?, 0xc0001d2230)
	/go/gorse/base/search/ivf.go:294 +0x175
github.com/zhenghaoz/gorse/master.(*Master).findItemNeighborsIVF(0xc0001c3a40, 0xc000576360, {0x30943b0, 0x0, 0x0}, {0xc00196e000, 0x84a, 0x84a}, 0xc0011e8fc0, 0xc0004e00e0)
	/go/gorse/master/tasks.go:464 +0x48a
github.com/zhenghaoz/gorse/master.(*FindItemNeighborsTask).run(0xc000a8cb70, 0x1813c43?)
	/go/gorse/master/tasks.go:325 +0x61e
github.com/zhenghaoz/gorse/master.(*Master).RunPrivilegedTasksLoop.func2({0x1e13090, 0xc000a8cb70})
	/go/gorse/master/master.go:330 +0x18c
created by github.com/zhenghaoz/gorse/master.(*Master).RunPrivilegedTasksLoop
	/go/gorse/master/master.go:326 +0x74e
```

i'm using zhenghaoz/gorse-in-one:latest. i do have a lot of unknown items (auto_insert is disabled), fwiw

after i've changed `recommend.item_neighbors.enable_index` from `true` to `false`, this issue has gone away

**Comment by bijak** [comment]
Just wanted to chime in to say that I was having this issue as well, though I do have auto-inserting of items and users on. Turning the indexing off for items fixed the crash there, but now the same crash happens just on building the user index instead
